#!/usr/bin/env python
# vim: set expandtab:
import sys
import surrogate_conf

def usage():
    print 'Usage: %s <command> <action> [args]' % sys.argv[0]

if __name__ == "__main__":
    try:
        m = __import__ ("surrogate_cmd_"+sys.argv[1])
        func = getattr(m, "action_"+sys.argv[2])
        func()
    except AttributeError:
        print "Command '%s' has no action: %s" % (sys.argv[1], sys.argv[2])
        usage()
    except ImportError:
        print "Invalid command: %s" % sys.argv[1]
        usage()
    except IndexError:
        usage()



